name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  setup-deps:
    name: Setup System Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Install X11 and OpenGL headers
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libgl1-mesa-dev libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev

  lint:
    name: Lint and Vet
    runs-on: ubuntu-latest
    needs: setup-deps
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Check formatting
        run: go fmt ./...
      - name: Run go vet
        run: go vet ./...
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.59.0
          args: run --timeout 5m

  test:
    name: Test with Race Detector
    runs-on: ubuntu-latest
    needs: setup-deps
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Run tests
        run: go test ./... -race -coverprofile=coverage.out
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.out
